graph TD;

    %% Data Bases %%

    %% Results %%

    NS[Not Suspicious]
    S[Suspicious]
    
    %% Events %%

    DM(Detected Motion)

    CPRfO(Caught Person Reaching for Object)
    PPRO(Caught Person Returning Object)
    PWPC(Person Walking Pass Cashier)

    %% Suspicious Events
    CPUO(Caught Person Using Object)
    PPBO(Caught Person Putting Object Inside Bag)

    %% Footage Events
    FFP5M(Footage Frame Passed 5 minutes)

    %% Actions %%

    SCF[Surveillance Camera Feed]
    IP[Image processing]
    FE[Feature Extraction]
    CM[Continue Monitoring]

    %% Alerting Actions
    AlSe[Alert Security]
    MO[Messsage Owner]
    SFtoOwn[Send Footage to Owner]

    %% Footage Actions
    DEF[Delete Expired Footage]
    BFs[Blur face]
    UBFs[Unblur face]

    %% Tagging Types 
    TSCt[Tag Object as Shopping Cart]

    %% Shoplifter Actions
    UtS[Untrack Shoplifter]

    %% Process Types
    PO[Process Objects]
    PP[Process People]
    POT[Process Object Type]
    PPA[Process Person's Accessories - masks, clothing]

    %% Track Types
    TPfO[Track Position Of Object]
    TPfP[Track Position Of Person]
    TFT[Track Frame Time]
    TPfPA[Track Position Of Person's Accessories]

    TS[Track Shoplifter]
    UtS[Untrack Shoplifter]

    TPfPPP[Track Pose Points Of Person]

    %% Conditions %%

    ISA{Is Suspicious Activity}
    IsP{Is Person}
    IsO{Is Object}
    IsSCt{Is Shopping Cart}
    IsA{Is Accessory}
    ITP{Is There Person}
    DPPfP{Did Person Pay For Products}
    DPhSCt{Did Person Have Shop Cart}

    %% Connections %%

    subgraph Camera
        SCF
    end

    subgraph AI Model


        subgraph Processing
            SCF --> IP
            IP --> FE

            subgraph Physical Features Extraction
                %% Person Feature Extraction
                FE --> PP

                PP --> IsP

                IsP --True--> TPfP
                IsP --True--> TPfPPP
                IsP --> DPhSCt

                %% Object Feature Extraction
                FE --> PO
                PO --> IsO
                IsO --True--> TPfO
                IsO --True--> PPA
                IsO --True--> POT

                DPhSCt --True--> TPfO

                POT --> IsSCt

                IsSCt --True--> TSCt

                PPA --> IsA
                IsA --True--> TPfPA
            end
            
            %% Movement Tracking
            subgraph Movement Tracking
                TPfPA --> DM
                TPfP --> DM
                TPfPPP --> DM
                TPfO --> DM

                DM --> CPRfO
                DM --> PWPC

                PWPC --> DPPfP
                
                %% Motion Condition
                DM -- motion --> ISA
                DM --> ITP
                ITP -- True --> BFs

                %% When there is Suspicious Activity
                ISA --> CPUO
                ISA --> PPBO

                CPUO --True--> S
                PPBO --True--> S
                DPPfP --False--> S

                S --> UBFs

                %% When there isn't Suspicious Activity
                ISA -- False --> NS
                NS --> CM
            end
            
            subgraph Alerting
                S --> AlSe

                AlSe --> MO
                AlSe --> SFtoOwn
            end

            subgraph Suspect Tracking
                 AlSe --> TS

                 TS --> PPRO
                 PPRO --> UtS
                 PPRO --> BFs
            end

            subgraph Frame Tracking
                SCF --> TFT --> FFP5M
                FFP5M --> ISA
                NS --> DEF

            end
        end
    end
